### ISSUE TITLE
One mixer image carries too many tags

### ISSUE THREAD

**Issue by yutongz** [istio-releases/daily-release#102]
mixer/mixer_debug images seem to be messed up a little. Multiple daily tags pointing to the same image.

https://pantheon.corp.google.com/gcr/images/istio-release/GLOBAL/mixer?project=istio-release&organizationId=433637338589&gcrImageListsize=50

https://pantheon.corp.google.com/gcr/images/istio-release/GLOBAL/mixer_debug?project=istio-release&organizationId=433637338589&gcrImageListsize=50

**Comment by yutongz** [comment]
@mattdelco @silverdev 

BTW @chxchx   Can you add me into this repo/org?

**Comment by mattdelco** [comment]
There isn't necessary a problem.  If there hasn't been any code changes to mixer then the docker images can end up being identical. A reason why only mixer exhibits this behavior is because it's using bazel to make the docker images and bazel tried hard to keep builds repeatable (e.g., it hard-codes all the file timestamps to 1/1/1970). The other components call "docker build" rather than "bazel build" to create their images.

**Comment by yutongz** [comment]
OK IC, I think you are right. There was no update in green-build during those releases.

Well I am not sure if it's necessary to change it, but feel like it's a bit confusing when people seeing this situation. I understand that usually developers are not going to directly look at that place, but still, confusing I guess.

Since we are thinking about changing/replacing bazel,  I suppose we can change this behavior at that time.

**Comment by chxchx** [comment]
@yutongz Invitation sent

**Comment by mattdelco** [comment]
From my perspective I think this is desirable behavior (i.e., mixer is showing a good example) and if we had reproducible builds then we'd see the behavior in other components too (or at least the ones that don't embed the version string in their executable binaries).  If the source hasn't changed then the bits generated should be the same (and the builds might go slightly faster too since 'docker' doesn't bother to upload layers that are already present in the registry).

**Comment by rkpagadala** [comment]
This is the normal way docker images are supposed to work. It is not confusing for an image to have multiple tags. That's normal.
